# Generated by Django 2.1 on 2018-08-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireless_printing', '0002_userdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'UserData'},
        ),
    ]
